baseurl = "https://blog.tomecek.net/"
languageCode = "en-us"
title = "Blog | Tomáš Tomeček"
theme = "hugo-steam-theme"
disqusShortname = "tomastomecek"
paginate = 7
rssLimit = 7
googleAnalytics = "G-J1S1CFZG1B"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"

[params]
  title = "Tomáš Tomeček"
  subtitle = "blog"
  copyright = 'This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'
  footerApendix = "[theme](https://github.com/digitalcraftsman/hugo-steam-theme) | [hugo](https://gohugo.io/) | [netlify](https://www.netlify.com/)"

  # You can choose between green, orange, red and blue.
  themeColor = "green"
  # Enable Google Analytics be inserting your tracking code

  # To provide some metadata for search engines and the about section in the footer
  # feel free to add a few information about you and your website.
  name = "Tomáš Tomeček"
  bio = "Tall software engineer, teacher, speaker, coder, linux enthusiast, gardener, hiker."
  description = "Technical blog. Read about Linux, Python, Containers, Red Hat, Fedora, tools."
  location = "Brno, Czech Republic"
  twitter = "TomasTomec"
  github = "TomasTomecek"

  # Enable a comment system
  # You can choose between Disqus or Google Plus by setting comments
  # to disqus or googleplus. For using Disqus you need to enter your
  # shortname in disqusShortname at the top of the configs. 
  comments = "disqus"

  # Customize or translate the strings
  keepReadingStr = "Keep reading"
  backtotopStr = "Back to top"
  shareStr = "Share"
  pageNotFoundTitle = "404 - Page not found"
  useSummaryIfNoDescription = true
[params.author]
  name = 'Tomas Tomecek'
